services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: parte2_front
    ports:
      - "8081:80"

networks:
  appnet:
    driver: bridge

volumes:
  db_data:

